# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"1\n\x0c\x43lientStatus\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\x0eTaskAssignment\x12\x0c\n\x04task\x18\x01 \x01(\t\"/\n\nTaskResult\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32]\n\x0bTaskService\x12-\n\x0bRequestTask\x12\r.ClientStatus\x1a\x0f.TaskAssignment\x12\x1f\n\nSendResult\x12\x0b.TaskResult\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTSTATUS']._serialized_start=14
  _globals['_CLIENTSTATUS']._serialized_end=63
  _globals['_TASKASSIGNMENT']._serialized_start=65
  _globals['_TASKASSIGNMENT']._serialized_end=95
  _globals['_TASKRESULT']._serialized_start=97
  _globals['_TASKRESULT']._serialized_end=144
  _globals['_ACK']._serialized_start=146
  _globals['_ACK']._serialized_end=168
  _globals['_TASKSERVICE']._serialized_start=170
  _globals['_TASKSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
